# Data sourcing

In [1]:
%%bash
mkdir -p data
curl -s https://wagon-public-datasets.s3.amazonaws.com/02-Data-Toolkit/02-Data-Sourcing/co2_sample.csv > data/co2_sample.csv
head -n 5 data/co2_sample.csv

country,2014,2015,2016,2017,2018,2019,2020,2021,2022
Afghanistan,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
Angola,1.64,1.22,1.18,1.15,1.12,1.15,1.12,1.2,1.23
Albania,2.25,2.04,2.01,2.13,2.08,2.05,2.0,2.12,2.1
Andorra,5.83,5.97,6.07,6.27,6.12,6.06,5.63,5.97,5.91

# Reading CSV with pandas

In [2]:
import pandas as pd

emission_df = pd.read_csv('./data/co2_pcap_cons.csv')
emission_df

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.28,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
1,Angola,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,...,1.28,1.640,1.220,1.180,1.150,1.120,1.150,1.120,1.200,1.230
2,Albania,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.27,2.250,2.040,2.010,2.130,2.080,2.050,2.000,2.120,2.100
3,Andorra,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,...,5.9,5.830,5.970,6.070,6.270,6.120,6.060,5.630,5.970,5.910
4,UAE,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,...,27,26.800,27.000,26.700,23.900,23.500,21.200,19.700,20.700,21.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Samoa,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.04,1.090,1.210,1.260,1.290,1.320,1.370,1.310,1.400,1.430
190,Yemen,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.994,0.937,0.480,0.377,0.363,0.356,0.365,0.362,0.387,0.395
191,South Africa,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,6.2,6.100,5.760,5.680,5.550,5.420,5.680,5.110,5.080,5.180
192,Zambia,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,...,0.511,0.560,0.519,0.471,0.474,0.467,0.487,0.388,0.416,0.424
193,Zimbabwe,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,...,0.906,0.929,0.955,0.821,0.708,0.830,0.783,0.737,0.789,0.804

# Getting bit more info

In [3]:
!curl -s https://wagon-public-datasets.s3.amazonaws.com/02-Data-Toolkit/02-Data-Sourcing/iso2_with_region.csv > data/iso2_with_region.csv
iso_df = pd.read_csv('data/iso2_with_region.csv', na_filter=False)
iso_df.head()

             Name Code       Full Name   Region
0     Afghanistan   AF     Afghanistan     Asia
1   Åland Islands   AX   Åland Islands   Europe
2         Albania   AL         Albania   Europe
3         Algeria   DZ         Algeria   Africa
4  American Samoa   AS  American Samoa  Oceania

In [4]:
emission_df

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Afghanistan,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.28,0.253,0.262,0.245,0.247,0.254,0.261,0.261,0.279,0.284
1,Angola,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,...,1.28,1.640,1.220,1.180,1.150,1.120,1.150,1.120,1.200,1.230
2,Albania,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.27,2.250,2.040,2.010,2.130,2.080,2.050,2.000,2.120,2.100
3,Andorra,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,...,5.9,5.830,5.970,6.070,6.270,6.120,6.060,5.630,5.970,5.910
4,UAE,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,...,27,26.800,27.000,26.700,23.900,23.500,21.200,19.700,20.700,21.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Samoa,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.04,1.090,1.210,1.260,1.290,1.320,1.370,1.310,1.400,1.430
190,Yemen,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.994,0.937,0.480,0.377,0.363,0.356,0.365,0.362,0.387,0.395
191,South Africa,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,6.2,6.100,5.760,5.680,5.550,5.420,5.680,5.110,5.080,5.180
192,Zambia,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,...,0.511,0.560,0.519,0.471,0.474,0.467,0.487,0.388,0.416,0.424
193,Zimbabwe,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,...,0.906,0.929,0.955,0.821,0.708,0.830,0.783,0.737,0.789,0.804

In [5]:
merged_df = emission_df.merge(iso_df, left_on='country', right_on='Name')
merged_df = merged_df.drop(columns=["country"])
merged_df

,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,...,2017,2018,2019,2020,2021,2022,Name,Code,Full Name,Region
0,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,0.247,0.254,0.261,0.261,0.279,0.284,Afghanistan,AF,Afghanistan,Asia
1,0.009,0.009,0.009,0.009,0.009,0.009,0.010,0.010,0.010,0.010,...,1.150,1.120,1.150,1.120,1.200,1.230,Angola,AO,Angola,Africa
2,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,...,2.130,2.080,2.050,2.000,2.120,2.100,Albania,AL,Albania,Europe
3,0.333,0.335,0.337,0.340,0.342,0.345,0.347,0.350,0.352,0.355,...,6.270,6.120,6.060,5.630,5.970,5.910,Andorra,AD,Andorra,Europe
4,0.063,0.063,0.064,0.064,0.064,0.064,0.065,0.065,0.065,0.065,...,23.900,23.500,21.200,19.700,20.700,21.100,UAE,AE,UAE,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,1.290,1.320,1.370,1.310,1.400,1.430,Samoa,WS,Samoa,Oceania
190,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,0.002,...,0.363,0.356,0.365,0.362,0.387,0.395,Yemen,YE,Yemen,Asia
191,0.003,0.003,0.004,0.004,0.004,0.004,0.004,0.004,0.004,0.004,...,5.550,5.420,5.680,5.110,5.080,5.180,South Africa,ZA,South Africa,Africa
192,0.255,0.256,0.257,0.258,0.259,0.260,0.261,0.262,0.263,0.264,...,0.474,0.467,0.487,0.388,0.416,0.424,Zambia,ZM,Zambia,Africa
193,0.059,0.060,0.060,0.060,0.060,0.061,0.061,0.061,0.061,0.062,...,0.708,0.830,0.783,0.737,0.789,0.804,Zimbabwe,ZW,Zimbabwe,Africa

## APIs

Making requests to the internet but in a machine readable way

In [6]:
import requests
from IPython.display import Image

url = "https://api.github.com/users/trouni"

response = requests.get(url).json()
Image(url = response['avatar_url'])

In [7]:
country_code = 'AE'
year = 2012

url = f"https://api.worldbank.org/v2/country/{country_code}/indicator/SP.POP.TOTL?date={year}&format=json"
response = requests.get(url).json()
response[1][0]['value']

7391448

In [9]:
def fetch_population_of_a_country(country, year):
    url = f"https://api.worldbank.org/v2/country/{country}/indicator/SP.POP.TOTL?date={year}&format=json"
    response = requests.get(url)
    data = response.json()

    if response.ok != True or data[1] == None:
        print('Failed')
        return None

    return data[1][0]["value"]

In [10]:
fetch_population_of_a_country('JP', 2023)

124516650